### ISSUE TITLE
Syntax error in list of projects

### ISSUE THREAD

**Issue by uandrae** [harphub/harp#6] opened 2020-08-04 13:41 UTC
Trying to install on ecgate I get:

```
> remotes::install_github("harphub/harp")
Downloading GitHub repo harphub/harp@master
Downloading GitHub repo harphub/harpSpatial@master
Error: Failed to install 'harp' from GitHub:
  Failed to install 'harpSpatial' from GitHub:
  Missing commas separating Remotes: 'harphub/meteogrid
  harphub/harpIO'
```

**Comment by andrew-MET** [comment] 2020-08-04 13:51
Duplicate of https://github.com/harphub/harpSpatial/issues/3

It's assigned to Alex, but I maybe he's on holiday.

**Comment by uandrae** [comment] 2020-08-04 13:55
OK, I can live without the spatial part for the time being.

**Closed** 2020-08-04 14:08 UTC
